// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAERyR3Sn3idRRHtboRgrr38yGeCZn0qD0',
    appId: '1:1063234158675:web:ecc34fe99319edc62cc6a6',
    messagingSenderId: '1063234158675',
    projectId: 'cardstorygame',
    authDomain: 'cardstorygame.firebaseapp.com',
    storageBucket: 'cardstorygame.appspot.com',
    measurementId: 'G-4D6WCXN2SY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZGz1vc6rU4KZGcIbNIex9M3FxMQiU9Gc',
    appId: '1:1063234158675:android:78a5d79f8c10037e2cc6a6',
    messagingSenderId: '1063234158675',
    projectId: 'cardstorygame',
    storageBucket: 'cardstorygame.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwEQgjuaOTw8bgrRzFUPBGVw1C_-ye2ZM',
    appId: '1:1063234158675:ios:ff262022291cd0e62cc6a6',
    messagingSenderId: '1063234158675',
    projectId: 'cardstorygame',
    storageBucket: 'cardstorygame.appspot.com',
    iosClientId:
        '1063234158675-ls1hv90jvethbkjff6qg0kjlm8jfueeu.apps.googleusercontent.com',
    iosBundleId: 'com.example.cardGame',
  );
}
