/*
const wordsMap = {
  "en": [
    {
      "word": "coloured",
      "sence": {
        "nl": "gekleurd",
        "ru": "цветной",
        "en": "coloured"
      },
      "word forms": [
      ],
      "cognate words": [
      ],
      "similar words": [
      ]
    },
    {
      "word": "dark blue",
      "sence": {
        "nl": "donkerblauw",
        "ru": "тёмно-синий",
        "en": "dark blue"
      },
      "word forms": [
      ],
      "cognate words": [
      ],
      "similar words": [
      ]
    },
    {
      "word": "grey",
      "sence": {
        "nl": "grijs",
        "ru": "серый",
        "en": "grey"
      },
      "word forms": [
      ],
      "cognate words": [
      ],
      "similar words": [
      ]
    },
    {
      "word": "brown",
      "sence": {
        "nl": "bruin",
        "ru": "коричневый",
        "en": "brown"
      },
      "word forms": [
      ],
      "cognate words": [
      ],
      "similar words": [
      ]
    },
    {
      "word": "бесцветный",
      "sence": {
        "nl": "kleurloos",
        "ru": "бесцветный",
        "en": "colourless"
      },
      "word forms": [
      ],
      "cognate words": [
      ],
      "similar words": [
      ]
    },
  ]
};
*/
import 'package:card_game/models/word_item.dart';
import 'package:card_game/models/word_sence.dart';
import 'package:card_game/models/word_sentense.dart';

const listWordMap = {
  "en": [
    "coloured",
    "dark blue",
    "grey",
    "brown",
    "colourless",
    "bad",
    "ordinary",
    "special",
    "bright",
    "sad",
    "different",
    "small",
    "big",
    "sweet",
    "slow",
    "fast",
    "strong",
    "weak",
    "young",
    "old",
    "cute",
    "naughty",
    "adult",
    "high",
    "which",
    "nice",
    "hot",
    "yummy",
    "low",
    "new",
    "long",
    "short",
    "wide",
    "narrow",
    "eldest",
    "married",
    "born",
    "best",
    "fun/comfortable",
    "live",
    "few",
    "elderly, old",
    "fresh",
    "liquid",
    "sweet",
    "dry",
    "cold",
    "warm",
    "delicious",
    "sour",
    "salty",
    "bitter",
    "spicy",
    "cooked",
    "healthy",
    "amazing",
    "better",
    "curious",
    "beautiful",
    "real",
    "expensive",
    "cheap",
    "waterproof",
    "quietly, softly",
    "sunny",
    "deep",
    "round",
    "whole",
    "own",
    "wet",
    "cloudy",
    "sad",
    "strong",
    "straight",
    "frosty",
    "artificial",
    "special",
    "historical",
    "sick",
    "glad",
    "terrible",
    "unemployed",
    "rigorous",
    "poor",
    "blind",
    "deaf",
    "heavy",
    "important",
    "precious",
    "tired",
    "angry",
    "finished",
    "boring",
    "simple",
    "smart",
    "english",
    "french",
    "dutch",
    "spanish",
    "difficult",
    "famous",
    "future",
    "free",
    "popular",
    "satisfied",
    "last",
    "scientific",
    "strongly",
    "obligated",
    "dangerous",
    "greedy",
    "friendly",
    "creative",
    "original",
    "brave",
    "independent",
    "desired",
    "lazy",
    "funny",
    "drunk",
    "busy",
    "red",
    "private",
    "even",
    "odd",
    "written",
    "obliged",
    "equals",
    "slim",
    "plump",
    "tight",
    "wide",
    "serious",
    "absent",
    "presents",
    "decently",
    "excellent",
    "naked",
    "thin",
    "ugly",
    "wide"
  ],
  "ru": [
    "цветной",
    "тёмно-синий",
    "серый",
    "коричневый",
    "бесцветный",
    "плохой",
    "обычный",
    "специальный",
    "яркий",
    "мрачный",
    "разные",
    "маленький",
    "большой",
    "милый",
    "медленный",
    "быстрый",
    "сильный",
    "слабый",
    "молодой",
    "старый",
    "милый",
    "непослушный",
    "взрослый",
    "высокий",
    "который",
    "хороший",
    "горячий",
    "вкусный",
    "низкий",
    "новый",
    "длинный",
    "короткий",
    "широкий",
    "узкий",
    "старший",
    "женатый/замужняя",
    "рожденный",
    "лучший",
    "веселый/уютный",
    "живой",
    "мало",
    "пожилой, старый",
    "свежий",
    "жидкий",
    "сладкий",
    "сухой",
    "холодный",
    "теплый",
    "вкусный",
    "кислый",
    "солёный",
    "горький",
    "острый",
    "готовый",
    "здоровый",
    "восхитительный",
    "лучше",
    "любопытный",
    "красивый",
    "настоящий",
    "дорогой",
    "дешевый",
    "непромокаемый",
    "тихо, мягко",
    "солнечный",
    "глубокий",
    "круглый",
    "целый",
    "собственный",
    "мокрый",
    "облачно",
    "грустно",
    "сильный, крепкий",
    "прямой",
    "морозный",
    "искусственный",
    "специальный",
    "исторический",
    "больной",
    "радостный",
    "ужасный",
    "безработный",
    "строгий",
    "бедный",
    "слепой",
    "глухой",
    "тяжелый",
    "важный",
    "ценный",
    "усталый",
    "сердитый",
    "готовый",
    "скучный",
    "простой",
    "умный",
    "английский",
    "французский",
    "голландский",
    "испанский",
    "трудный",
    "известный",
    "будущий",
    "свободный",
    "популярный",
    "довольный",
    "прошедший",
    "научный",
    "сильно",
    "обязанный",
    "опасный",
    "жадный",
    "дружелюбный",
    "творческий",
    "оригинальный",
    "смелый",
    "самостоятельный",
    "нужный",
    "ленивый",
    "смешной",
    "пьяный",
    "занятый",
    "красная",
    "личный",
    "четное",
    "нечетное",
    "письменный",
    "обязанный",
    "равный",
    "стройный",
    "полный",
    "тугой, в обтяжку",
    "широкий",
    "серьезный",
    "отсутствующий",
    "присутствующий",
    "прилично",
    "отличный",
    "голый",
    "тонкий",
    "уродливый",
    "широкий",
  ],
  "nl": [
    "gekleurd",
    "donkerblauw",
    "grijs",
    "bruin",
    "kleurloos",
    "slecht",
    "gewoon",
    "bijzonder",
    "helder",
    "somber",
    "verschillend",
    "klein",
    "groot",
    "lief",
    "langzaam",
    "snel",
    "sterk",
    "zwak",
    "jong",
    "oud",
    "lief",
    "stout",
    "volwassene",
    "hoog",
    "welke",
    "leuk",
    "heet",
    "lekker",
    "laag",
    "nieuw",
    "lang",
    "kort",
    "breed",
    "smal",
    "oudere",
    "getrouwd",
    "geboren",
    "best",
    "gezellig",
    "levend",
    "weinig",
    "bejaard",
    "vers",
    "vloeibaar",
    "zoet",
    "droog",
    "koud",
    "warm",
    "lekker",
    "zuur",
    "zout",
    "bitter",
    "pittig",
    "klaar",
    "gezond",
    "verrukkelijk",
    "liever",
    "nieuwsgierig",
    "mooi",
    "echt",
    "duur",
    "goedkoop",
    "waterdicht",
    "zacht",
    "zonnig",
    "diep",
    "rond",
    "heel",
    "eigen",
    "nat",
    "bewolkt",
    "triest",
    "hard",
    "recht",
    "vorstig",
    "kunstmatig",
    "speciaal",
    "historisch",
    "ziek",
    "blij",
    "verschrikkelijk",
    "werkloos",
    "streng",
    "arm",
    "blind",
    "doof",
    "zwaar",
    "belangrijk",
    "waard",
    "moe",
    "boos",
    "klaar",
    "saai",
    "eenvoudig",
    "slim",
    "engels",
    "frans",
    "nederlands",
    "spaans",
    "moeilijk",
    "bekend",
    "komende",
    "vrij",
    "populair",
    "tevreden",
    "afgelopen",
    "wetenschappelijk",
    "flink",
    "verplicht",
    "gevaarlijk",
    "gierig",
    "vriendelijk",
    "creatief",
    "origineel",
    "dapper",
    "zelfstandig",
    "nuttig",
    "lui",
    "grappig",
    "dronken",
    "bezig",
    "rooie",
    "persoonlijk",
    "even",
    "oneven",
    "schriftelijk",
    "verplicht",
    "gelijk",
    "slank",
    "gezet",
    "strak",
    "wijd",
    "serieus",
    "afwezig",
    "aanwezig",
    "netjes",
    "uitstekende",
    "bloot",
    "dun",
    "lelijk",
    "wijd",
  ],
  "lesson": [
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "1",
    "2",
    "2",
    "2",
    "2",
    "2",
    "2",
    "2",
    "2",
    "2",
    "2",
    "2",
    "2",
    "2",
    "3",
    "3",
    "3",
    "3",
    "3",
    "3",
    "3",
    "3",
    "3",
    "3",
    "3",
    "4",
    "4",
    "4",
    "4",
    "4",
    "4",
    "4",
    "4",
    "5",
    "5",
    "5",
    "5",
    "5",
    "5",
    "5",
    "5",
    "5",
    "5",
    "5",
    "5",
    "5",
    "5",
    "5",
    "6",
    "6",
    "6",
    "6",
    "6",
    "6",
    "7",
    "7",
    "7",
    "7",
    "7",
    "7",
    "7",
    "7",
    "7",
    "7",
    "7",
    "7",
    "7",
    "7",
    "8",
    "8",
    "8",
    "8",
    "8",
    "8",
    "9",
    "9",
    "9",
    "9",
    "10",
    "10",
    "10",
    "10",
    "10",
    "10",
    "10",
    "10",
    "10",
    "10",
    "10",
    "10",
    "10",
    "10",
    "10",
    "10",
    "10",
    "10",
    "10",
    "10",
    "10",
    "11",
    "11",
    "11",
    "11",
    "11",
    "11",
    "11",
    "11",
    "11",
    "11",
    "11",
    "11",
    "11",
    "11",
    "11",
    "12",
    "12",
    "12",
    "12",
    "12",
    "12",
    "12",
    "12",
    "12",
    "12",
    "2",
    "2",
    "2",
    "2",
    "3-6",
    "3-6",
    "3-6",
    "3-6"
  ],
  "nl_sentence": [
    "De regenboog is ^gekleurd^.",
    "De Noordzee is ^donkerblauw^.",
    "De muis is ^grijs^.",
    "Zijn auto is ^bruin^.",
    "De lucht is ^kleurloos^.",
    "Dit is een ^slecht^ voorbeeld.",
    "Dit is ook geen ^gewoon^ geval.",
    "Misschien ben je daarom zo ^bijzonder^.",
    "Ik zag een ^helder^ licht.",
    "Waarom ben je zo ^somber^?",
    "De incubatie-tijd is bij iedereen ^verschillend^.",
    "We hebben hier een ^klein^ muisje wonen.",
    "Deze doos is erg ^groot^.",
    "Wat een ^lief^ hondje.",
    "Doe niet zo ^langzaam^!",
    "Dus ik moet erg ^snel^ zijn.",
    "Je zei dat hij ^sterk^ was.",
    "Het signaal is wel erg ^zwak^.",
    "Ze ziet er ^jong^ uit, maar eigenlijk is ze ouder dan jou.",
    "Ik heb u mijn ^oud^ adres gegeven.",
    "Uiteraard, je bent zó ^lief^.",
    "Weer een ^stout^ kind?",
    "Onze zoon is nu ^volwassen^.",
    "Ik vind dat de prijs te ^hoog^ is.",
    "Een nobele gebaar ^welke^ zeer op prijs gesteld wordt.",
    "Ik denk dat het een ^leuk^ appartement is.",
    "Dat is ^heet^, weet je.",
    "Dit is ^lekker^, Cartman.",
    "De flat heeft een ^laag^ plafond.",
    "Ik heb gebeld en het ^nieuwe^ adres doorgegeven.",
    "We moeten ^lang^, serieus praten.",
    "Het was aangenaam, maar te ^kort^.",
    "Ik heb een breed bekken.",
    "Bovendien heb ik een erg smal bed.",
    "Ik ben drie jaar ouder dan mijn broer.",
    "We zijn al drie jaar getrouwd.",
    "Geboren om een krijger te zijn, kind van een prins.",
    "Ik ben de beste leerling van mijn klas.",
    "Je huis is zo gezellig.",
    "Het spijt me, maar ik mag de kreeften niet levend verkopen",
    "Ze had weinig vrienden.",
    "Mijn oma is al ^bejaard^.",
    "Er stond elke morgen vers sap op tafel.",
    "De astronauten eten ^vloeibaar^ voedsel.",
    "De cake was te zoet.",
    "Mijn kleren zijn nog niet droog.",
    "Het is erg ^koud^ voor maart.",
    "Geef deze jonge dame een ^warm^ drankje.",
    "Dank u, het diner was erg ^lekker^.",
    "Niet te zoet, niet te ^zuur^.",
    "^Zout^, als de zee.",
    "De koffie is precies zoals ik hem graag heb, zwart en ^bitter^.",
    "Uw ketchup is heel erg ^pittig^.",
    "De kip is klaar.",
    "Normaal gesproken leeft een gezond ge-zond persoon lang.",
    "Ja, het was ^verrukkelijk^.",
    "Ik zou hem ^liever^ niet bellen",
    "Hij werd ^nieuwsgierig^ en volgde haar.",
    "Chandler vindt je trui zo ^mooi^.",
    "Ik ben echt verliefd op jou.",
    "Gas is zo ^duur^.",
    "Het was geen ^goedkoop^, maar een duur parfum.",
    "Voor het geval het regent, heb ik een ^waterdicht^ jasje.",
    "Mijn bed is zo zacht.",
    "Het is zonnig zon-nig hier.",
    "Dit meer is niet zo diep.",
    "De aarde is rond.",
    "Dat is een heel belangrijk besluit.",
    "Ik schrijf mijn eigen boek.",
    "Mijn haar is erg nat.",
    "Vandaag is het minder bewolkt be-wolkt dan gisteren.",
    "Ik vind dit verhaal erg triest.",
    "Hij sloeg me heel hard.",
    "Ik moet recht zitten.",
    "De afgelopen winter was zo vorstig.",
    "Ik vind dat deze diamant kunstmatig is.",
    "Wij hebben een speciaal spe-ci-aal tarief voor werknemers.",
    "Dat is een historisch his-to-risch voorbeeld.",
    "Ik ben te ziek om boodschappen te doen.",
    "Mijn oma is heel blij.",
    "Deze situatie is verschrikkelijk.",
    "Nu ben ik werkloos werk-loos.",
    "Wij werken onder streng toezicht.",
    "Hij komt uit een arm land.",
    "Maria is blind aan haar rechteroog.",
    "Frankie is ^doof^, maar hij is goed in liplezen.",
    "Ja, maar hij had een ^zwaar^ jaar.",
    "Dat is heel belangrijk be-lang-rijk om samen te werken.",
    "Deze diamant is veel geld waard.",
    "Mijn moeder is erg moe.",
    "Ik vind het niet leuk als je ^boos^ bent.",
    "De kip is klaar.",
    "Zijn leven is heel saai en rustig.",
    "De redenen voor censuur zijn eenvoudig.",
    "Jullie zijn niet slim genoeg om me te begrijpen.",
    "Hij spreekt geen Engels En-gels.",
    "Ik spreek geen enkel woord Frans.",
    "Mijn opa spreekt nauwelijks Nederlands Ne-der-lands.",
    "Ik kan in het Spaans lezen.",
    "Dat is moeilijk moei-lijk te begrijpen.",
    "Hij is bekend be-kend in deze stad.",
    "Dit is mijn ^komende^ man.",
    "Mijn zus is vrij en onafhankelijk.",
    "Je bent erg populair po-pu-la-ir.",
    "Ik ben tevreden te-vre-den met mijn werk.",
    "Afgelopen af-ge-lo-pen jaar waren zij beste vrienden.",
    "Sommige dingen kun je niet wetenschappelijk we-ten-schap-pe-lijk definieren.",
    "Daan en Maria hadden een flink ruzie.",
    "Jij bent niet verplicht ver-plicht om te antwoorden.",
    "Hij is een heel gevaarlijk ge-vaar-lijk persoon.",
    "Jij bent zo gierig gie-rig.",
    "Eerlijk gezegd is hij niet zo vriendelijk vrien-de-lijk.",
    "Laten wij creatief cre-a-tief denken.",
    "Dat is een origineel o-ri-gi-neel exemplaar van de overeenkomst.",
    "Mijn zoon is zo dapper dap-per.",
    "Zij wil meer zelfstandig zelf-standig zijn.",
    "Deze informatie is heel nuttig nut-tig voor mij.",
    "Ik ben te lui.",
    "Ik vind het grappig grap-pig.",
    "Jullie dronken dron-ken te veel bier.",
    "Ik ben ^bezig^ be-zig met iets.",
    "Hij had wel een ^rooie^ neus.",
    "Ik heb van haar een persoonlijk per-soon-lijk bericht ontvangen.",
    "Is dat een even e-ven getal?",
    "Is dat een oneven on-e-ven getal?",
    "Op deze vraag moeten studenten schriftelijk beantwoorden.",
    "Jij bent niet verplicht ver-plicht om te antwoorden.",
    "De kansen moeten gelijk ge-lijk voor alle deelnemers zijn.",
    "Zij wil zo slank als haar oudere zus zijn.",
    "Hun dochter Hannie is een beetje gezet.",
    "Deze jurk zit te strak.",
    "Vorige nacht hield ik mijn ogen wijd open.",
    "De werkloosheid is een serieus se-rie-us probleem in onze stad.",
    "Morgen ben ik afwezig af-we-zig van school.",
    "Is hij aanwezig aan-we-zig op de vergadering?",
    "We willen dat je je ^netjes^ gedraagt.",
    "Dr. Shepherd is een ^uitstekende^ chirurg.",
    "Ik ben nog al ^bloot^ nu.",
    "Mijn vader zei: \"Nee, het ijs is te ^dun^\".",
    "Dit is een ^lelijk^ klein huisje.",
    "Vorige nacht hield ik mijn ogen wijd open.",
  ],
  "ru_sentence": [
    "Радуга цветная.",
    "Северное море темно-синего цвета.",
    "Мышь серого цвета.",
    "Его машина коричневого цвета.",
    "Воздух бесцветный.",
    "Это плохой пример.",
    "Это тоже не обычный случай.",
    "Может быть, именно поэтому ты такой особенный.",
    "Я увидел яркий свет.",
    "Почему ты такой мрачный?",
    "Инкубационный период у всех разный.",
    "У нас живет маленькая мышка.",
    "Эта коробка очень большая.",
    "Какая милая собачка.",
    "Не будь таким медлительным!",
    "Поэтому мне приходится действовать очень быстро.",
    "Вы сказали, что он сильный.",
    "Сигнал очень слабый.",
    "Она выглядит молодо, но на самом деле она старше вас.",
    "Я дал вам свой старый адрес.",
    "Конечно, ты такая милая.",
    "Еще один непослушный ребенок?",
    "Наш сын уже ^взрослый^.",
    "Я считаю, что цена слишком ^высокая^.",
    "Благородный жест, который очень ценится.",
    "Я думаю, что это хорошая квартира.",
    "Это ^горячо^, ты знаешь.",
    "Это ^вкусно^, Картман.",
    "В квартире ^низкий^ потолок.",
    "Я позвонил и назвал ^новый^ адрес.",
    "Нам предстоит ^длинный^ и серьезный разговор.",
    "Это было приятно, но слишком коротко.",
    "У меня широкий таз.",
    "Кроме того, у меня очень узкая кровать.",
    "Я на три года старше своего брата.",
    "Мы женаты уже три года.",
    "Рожденный быть воином, дитя принца.",
    "Я лучший ученик в своем классе.",
    "Ваш дом такой уютный.",
    "Извините, но мне нельзя продавать омаров живыми.",
    "У нее было мало друзей.",
    "Моя бабушка уже пожилая.",
    "Каждое утро на столе был свежий сок.",
    "Астронавты питаются жидкой пищей.",
    "Торт был слишком сладким.",
    "Моя одежда еще не высохла.",
    "Для марта очень холодно.",
    "Дайте этой молодой леди горячий напиток.",
    "Спасибо, ужин был очень вкусным.",
    "Не слишком сладкий, не слишком кислый.",
    "Солёный, как море",
    "Кофе именно такой, какой я люблю - черный и горький.",
    "Ваш кетчуп очень острый.",
    "Курица готова.",
    "Обычно здоровый человек живет долго.",
    "Да, это было восхитительно.",
    "Я бы не стал звонить ему.",
    "Ему стало любопытно, и он последовал за ней.",
    "Чендлеру очень нравится твой джемпер.",
    "Я по-настоящему влюблен в тебя.",
    "Бензин очень дорогой.",
    "Это был не дешевый, а дорогой парфюм.",
    "На случай дождя у меня есть водонепроницаемая курточка.",
    "Моя кровать такая мягкая.",
    "Здесь солнечно.",
    "Это озеро не такое уж и глубокое.",
    "Земля круглая.",
    "Это очень важное решение.",
    "Я пишу собственную книгу.",
    "Мои волосы очень сырые.",
    "Сегодня менее облачно, чем вчера.",
    "Я считаю эту историю очень грустной.",
    "Он ударил меня очень сильно.",
    "Я должен сидеть прямо.",
    "Прошлая зима была очень морозной.",
    "Я думаю, что этот алмаз искусственный.",
    "У нас есть специальные тарифы для сотрудников.",
    "Это исторический пример.",
    "Я слишком болен, чтобы идти в магазин.",
    "Моя бабушка очень рада.",
    "Это ужасная ситуация.",
    "Сейчас я безработный.",
    "Мы работаем под строгим надзором.",
    "Он из бедной страны.",
    "Мария слепая на правый глаз.",
    "Фрэнки глухой, но он хорошо читает по губам.",
    "Да, но у него был трудный год.",
    "Очень важно работать вместе.",
    "Этот бриллиант стоит больших денег.",
    "Моя мама очень устала.",
    "Мне не нравится, когда ты злишься.",
    "Курица готова.",
    "Его жизнь очень скучная и тихая.",
    "Причины цензуры просты.",
    "Вы недостаточно умны, чтобы понять меня.",
    "Он не говорит по-английски.",
    "Я ни говорю ни слова по-французски.",
    "Мой дедушка почти не говорит по-нидерландски.",
    "Я могу читать на испанском языке.",
    "Это сложно понять.",
    "Его знают в этом городе.",
    "Это мой ^будущий^ муж.",
    "Моя сестра свободная и независимая.",
    "Ты популяренрна.",
    "Я доволен своей работой.",
    "В прошлом году они были лучшими друзьями.",
    "Некоторым вещам нельзя дать научное определение.",
    "Дан и Мария очень серьезно поссорились.",
    "Ты не обязан отвечать.",
    "Он очень опасный человек.",
    "Ты такой жадный.",
    "Честно говоря, он не такой уж и дружелюбный.",
    "Давайте мыслить нестандартно.",
    "Это оригинал договора.",
    "Мой сын такой смелый.",
    "Она хочет быть более независимой.",
    "Эта информация очень полезна для меня.",
    "Я слишком ленивый.",
    "Я считаю это смешным.",
    "Вы выпили слишком много пива.",
    "Я кое-чем ^занят^.",
    "У него был красный нос.",
    "Я получил от нее личное сообщение.",
    "Это четное число?",
    "Это нечестное число?",
    "На этот вопрос студенты должны ответить в письменном виде.",
    "Ты не обязан отвечать.",
    "Шансы должны быть равными для всех участников.",
    "Она хочет быть такой же стройной, как и ее старшая сестра.",
    "Их дочь Ханни немного полненькая.",
    "Это платье слишком тесное.",
    "Прошлой ночью я держал свои глаза широко открытыми / Прошлой ночью я не мог сомкнуть глаз.",
    "Безработица – это серьезная проблема в нашем городе.",
    "Завтра меня не будет в школе.",
    "Он присутствует на собрании?",
    "Мы хотим, чтобы вы вели себя прилично.",
    "Доктор Шепард - отличный хирург.",
    "Теперь я совсем голый.",
    "Мой отец сказал: \"Нет, лед слишком тонкий\".",
    "Это уродливый маленький дом.",
    "Прошлой ночью я держал свои глаза широко открытыми / Прошлой ночью я не мог сомкнуть глаз.",
  ],
  "en_sentence": [
    "The rainbow is coloured.",
    "The North Sea is dark blue.",
    "The mouse is gray.",
    "His car is brown.",
    "The air is colorless.",
    "This is a bad example.",
    "This is not an ordinary case either.",
    "Maybe that\'s why you\'re so special.",
    "I saw a bright light.",
    "Why are you so sad?",
    "The incubation period is different for everyone.",
    "We have a little mouse.",
    "This box is very big.",
    "What a sweet dog.",
    "Don\'t be so slow!",
    "So I have to act very fast.",
    "You said he was strong.",
    "The signal is very weak.",
    "She looks young, but actually she is older than you.",
    "I gave you my old address.",
    "Of course, you are so cute.",
    "Another naughty child?",
    "Our son is an ^adult^ now.",
    "I think that the price is too ^high^.",
    "A noble gesture which is much appreciated.",
    "I think it\'s a nice apartment.",
    "That\'s ^hot^, you know.",
    "This is ^yummy^, Cartman.",
    "The flat has a ^low^ ceiling.",
    "I called and gave the ^new^ address.",
    "We need to have a ^long^, serious talk.",
    "It was pleasant, but too short.",
    "I have a wide pelvis.",
    "Also, my bed is very narrow.",
    "I am three years older than my brother.",
    "We have been married for three years.",
    "Born to be a warrior, child of a prince.",
    "I am the best student in my class.",
    "Your home is so comfortable.",
    "I\'m sorry, but I\'m not allowed to sell the lobsters live.",
    "She had few friends.",
    "My grandmother is already elderly.",
    "There was fresh juice on the table every morning.",
    "The astronauts eat liquid food.",
    "The cake was too sweet.",
    "My clothes are not dry yet.",
    "It\'s very cold for March.",
    "Give this young lady a hot drink.",
    "Thank you, the dinner was very delicious.",
    "Not too sweet, not too sour.",
    "Salt, like the sea.",
    "The coffee is exactly how I like it, black and bitter.",
    "Your ketchup is very spicy.",
    "The chicken\'s ready.",
    "A healthy person usually lives a long life.",
    "Yes, it was amazing.",
    "I would ^like^ not to call him",
    "He became curious and followed her.",
    "Chandler likes your sweater so much.",
    "I\'m truly in love with you.",
    "Gas is so expensive.",
    "It was not a cheap, but an expensive perfume.",
    "In case it rains, I have a waterproof jacket.",
    "My bed is so soft.",
    "It\'s sunny here.",
    "This lake is not so deep.",
    "The Earth is round.",
    "This is a very important decision.",
    "I\'m writing my own book.",
    "My hair is really wet.",
    "It\'s less cloudy today than yesterday.",
    "I think this story is very sad.",
    "He hit me very hard.",
    "I have to sit straight.",
    "The past winter was so cold.",
    "I think this diamond is artificial.",
    "We have a special rate for employees.",
    "This in an example from history.",
    "I\'m too sick to go for groceries.",
    "My grandma is very happy.",
    "This situation is horrible.",
    "I\'m unemployed at the moment.",
    "We work under strict supervision.",
    "He is from a poor country.",
    "Maria is blind in her right eye.",
    "Frankie is deaf, but he is good at lip reading.",
    "Yeah, but he\'s had a heavy year.",
    "It\'s important to work together.",
    "This diamond is worth a lot of money.",
    "My mother is really tired.",
    "I don\'t like it when you are angry.",
    "The chicken\'s ready.",
    "His life is very boring and quiet.",
    "The reasons for censorship are simple.",
    "You\'re not smart enough to understand me.",
    "He doesn\'t speak English.",
    "I don\'t speak a single word of French.",
    "My grandpa barely speaks any Dutch.",
    "I can read in Spanish.",
    "This is difficult to understand.",
    "He is known in this town.",
    "This is my ^future^ husband.",
    "My sister is free and independent.",
    "You\'re very popular.",
    "I\'m satisfied with my work.",
    "They were best friends the last year.",
    "Some things cannot be defined scientifically.",
    "Daan and Maria had a really big fight.",
    "You\'re not required to answer.",
    "He is a very dangerous person.",
    "You\'re so greedy.",
    "To be honest, he is not so friendly.",
    "Let\'s think outside the box. / Let\'s be creative.",
    "This is an original copy of the contract.",
    "My son is so brave.",
    "She wants to be more independent.",
    "This information is very useful to me.",
    "I\'m too lazy.",
    "I think it\'s funny.",
    "You drank too much beer.",
    "I\'m ^busy^ with something.",
    "He did have a red nose.",
    "I have received a personal message from her.",
    "Is this an even number?",
    "Is this an odd number?",
    "Students have to answer to this question in writing.",
    "You\'re not required to answer.",
    "The chances should be equal for all participants.",
    "She wants to be as thin as her older sister.",
    "Their daughter Hannie is a bit overweight.",
    "This dress is too tight.",
    "Last night I kept my eyes wide open.",
    "The unemployment is a serious problem in our town.",
    "Tomorrow I\'m going to be absent from school.",
    "Is he at the meeting?",
    "We want you to behave decently.",
    "Dr. Shepherd is an excellent surgeon.",
    "I\'m naked right now.",
    "My father said, \"No, the ice is too thin.\"",
    "This is an ugly little house.",
    "Last night I kept my eyes wide open."
  ]
};

Map<String, List<WordItem>> generateListWordItems() {
  var nlSentences = listWordMap["nl_sentence"] ?? [];
  var ruSentences = listWordMap["ru_sentence"] ?? [];
  var enSentences = listWordMap["en_sentence"] ?? [];
  var lesson = listWordMap["lesson"] ?? [];
  var nl = listWordMap["nl"] ?? [];
  var ru = listWordMap["ru"] ?? [];
  var en = listWordMap["en"] ?? [];

  print(
      "Длинны массивов = ${nlSentences.length}, ${ruSentences.length}, ${enSentences.length}, ${lesson.length}, ${nl.length}, ${ru.length}, ${en.length}");
  if (nlSentences.length != ruSentences.length &&
      ruSentences.length != enSentences.length &&
      enSentences.length != lesson.length &&
      lesson.length != nl.length &&
      nl.length != ru.length  &&
      ru.length != en.length) {
    return {"nl_words": [], "ru_words": [], "en_words": []};
  }

  List<WordItem> nlItems = [];
  List<WordItem> ruItems = [];
  List<WordItem> enItems = [];
  List<int> lessonList = [];
  for (int i = 0; i < lesson.length; i++) {
    lessonList = lesson[i].contains('-')
        ? lesson[i].split('-').map((e) => int.tryParse(e) ?? -1).toList()
        : [int.tryParse(lesson[i]) ?? -1];

    nlItems.add(WordItem(
      index: i,
      word: nl[i],
      sence: WordSence(nl: [nl[i]], ru: [ru[i]], en: [en[i]]),
      lesson: lessonList,
      sentence: WordSentence(
        nlSentence: nlSentences[i],
        ruSentence: ruSentences[i],
        enSentence: enSentences[i],
      ),
      wordForms: [],
      cognateWords: [],
      similarWords: [],
    ));
    ruItems.add(WordItem(
      index: i,
      word: ru[i],
      sence: WordSence(nl: [nl[i]], ru: [ru[i]], en: [en[i]]),
      lesson: lessonList,
      sentence: WordSentence(
        nlSentence: nlSentences[i],
        ruSentence: ruSentences[i],
        enSentence: enSentences[i],
      ),
      wordForms: [],
      cognateWords: [],
      similarWords: [],
    ));
    enItems.add(WordItem(
      index: i,
      word: en[i],
      sence: WordSence(nl: [nl[i]], ru: [ru[i]], en: [en[i]]),
      lesson: lessonList,
      sentence: WordSentence(
        nlSentence: nlSentences[i],
        ruSentence: ruSentences[i],
        enSentence: enSentences[i],
      ),
      wordForms: [],
      cognateWords: [],
      similarWords: [],
    ));
  }
  var items = {
    "nl_words": nlItems,
    "ru_words": ruItems,
    "en_words": enItems,
  };
  return items;
}
